<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://helloservice.jaxws.alekseysamoylov.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="FibonacciServiceService" targetNamespace="http://helloservice.jaxws.alekseysamoylov.com/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://helloservice.jaxws.alekseysamoylov.com/" elementFormDefault="unqualified" targetNamespace="http://helloservice.jaxws.alekseysamoylov.com/" version="1.0">
            <xs:element name="calculate" type="tns:calculate"/>
            <xs:element name="calculateResponse" type="tns:calculateResponse"/>
            <xs:complexType name="calculate">
                <xs:sequence>
                    <xs:element name="arg0" type="xs:int"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="calculateResponse">
                <xs:sequence>
                    <xs:element name="return" type="xs:int"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="calculateResponse">
        <wsdl:part element="tns:calculateResponse" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="calculate">
        <wsdl:part element="tns:calculate" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="FibonacciService">
        <wsdl:operation name="calculate">
            <wsdl:input message="tns:calculate" name="calculate"></wsdl:input>
            <wsdl:output message="tns:calculateResponse" name="calculateResponse"></wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="FibonacciServiceServiceSoapBinding" type="tns:FibonacciService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="calculate">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="calculate">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="calculateResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="FibonacciServiceService">
        <wsdl:port binding="tns:FibonacciServiceServiceSoapBinding" name="FibonacciServicePort">
            <soap:address location="http://localhost:8080/jaxws-example-1.0-SNAPSHOT/fibonacci-service"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>